stadline_status_page_homepage:
    pattern:  /status
    defaults: { _controller: StadlineStatusPageBundle:Status:index}
    
stadline_status_page_params:
    pattern:  /status/params
    defaults: { _controller: StadlineStatusPageBundle:Status:exposeParams }
