parameters:
    stadline_status_page.symfony.requirement.class: StadLine\StatusPageBundle\Requirements\SymfonyRequirements
    stadline_status_page.requirement.collections.class: StadLine\StatusPageBundle\Requirements\RequirementCollections
    stadline_status_page.version.requirement.class: StadLine\StatusPageBundle\Requirements\VersionRequirements
    stadline_status_page.api.requirement.class: StadLine\StatusPageBundle\Requirements\ApiRequirements

services:
    stadline_status_page.version.requirement:
        class: %stadline_status_page.version.requirement.class%
        arguments: [@service_container]
        tags:
          - { name: status_page.requirement}

    stadline_status_page.requirement.collections:
        class: %stadline_status_page.requirement.collections.class%

    stadline_status_page.symfony.requirement:
        class: %stadline_status_page.symfony.requirement.class%
        tags:
          - { name: status_page.requirement}

    stadline_status_page.api.requirement:
        class: %stadline_status_page.api.requirement.class%
        arguments: [@service_container]
        tags:
         - { name: status_page.requirement}
