parameters:
    stadline_status_page.symfony.requirement.class: 'Stadline\StatusPageBundle\Requirements\SymfonyRequirements'
    stadline_status_page.requirement.collections.class: 'Stadline\StatusPageBundle\Requirements\RequirementCollections'
    stadline_status_page.version.requirement.class: 'Stadline\StatusPageBundle\Requirements\VersionRequirements'
    stadline_status_page.statuscode.handler.class: 'Stadline\StatusPageBundle\Handler\StatusCodeHandler'

services:
    stadline_status_page.version.requirement:
        class: '%stadline_status_page.version.requirement.class%'
        arguments: ['@service_container']
        public: true
        tags:
          - { name: 'status_page.requirement' }

    stadline_status_page.requirement.collections:
        class: '%stadline_status_page.requirement.collections.class%'
        public: true

    stadline_status_page.symfony.requirement:
        class: '%stadline_status_page.symfony.requirement.class%'
        public: true
        tags:
          - { name: 'status_page.requirement' }

    stadline_status_page.statuscode.handler:
        class: '%stadline_status_page.statuscode.handler.class%'
        public: true
        tags:
          - { name: 'status_page.handler' }
