language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=dev-master

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: 7.0

before_script:
    - composer install

script:
    - phpunit
